name: DivCore
main: me.felnstaren.divcore.DivCore
version: 1.0.1a
author: Felnstaren
description: Server development utilities
api-version: 1.16

commands:
 dchat:
  aliases: [dc]
  description: DivCore base chat command