chat:
 chat-group: "default"
 chat-format: "group"
 chat-color: "group"
 prefix: "%group%"
 suffix: "%group%"
 name-color: "group"
 chat-channel: "global"

metrics:
 first-join-date: none
 join-date: none
 play-time: none

punishment:
 muted: 0s